name: sj_Expansion

author: czssj_

description: A Slimefun4-Addon with some memes and some interesting things

main: me.czssj_.sj_expansion.sj_Expansion

website: https://github.com/czszzh/sj_Expansion

version: ${project.version}

api-version: 1.14

depend:
- Slimefun
- InfinityExpansion
- FluffyMachines

softdepend:
- RykenSlimefunCustomizer
- GuizhanLibPlugin